a_records:
  - { host: sumo }
  - { host: warden }
  - { subdomain: jellyfin, host: sumo }
  - { subdomain: influxdb, host: sumo }
  - { subdomain: grafana, host: sumo }
  - { subdomain: transmission, host: sumo }