---
- name: Create nginx config directory
  tags:
    - nginx
  file:
    path: '/var/nginx/config'
    state: directory

- name: Copy nginx config
  tags:
    - nginx
  copy:
    src: 'files/custom.conf'
    dest: '/var/nginx/config'

- name: Update and run the nginx proxy container
  tags:
    - nginx
  docker_container:
    name: nginx
    image: jwilder/nginx-proxy:latest
    pull: yes
    recreate: yes
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/config/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    ports:
      - '80:80'
      - '443:443'
    network_mode: bridge
    networks:
      - name: docker_net

- name: Open http(s) ports in firewalld
  tags:
    - nginx
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  loop:
    - '80/tcp'
    - '443/tcp'