---
- name: Ensure the host media folder exists
  tags:
    - jellyfin
  file:
    path: '{{ host_media_directory }}'
    state: directory

- name: Update and run the jellyfin container
  tags:
    - jellyfin
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin:latest
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - jellyfin_config:/config
      - '{{ host_media_directory  }}:/media'
    env:
      TZ: America/Eastern
    network_mode: host

- name: Open port in firewalld
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  loop:
    - '8096/tcp'
    - '1900/udp'