---
- name: Ensure the host media folder exists
  tags:
    - jellyfin
  file:
    path: '{{ host_media_directory }}'
    state: directory

- name: Update and run the jellyfin container
  tags:
    - jellyfin
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin:latest
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - jellyfin_config:/config
      - '{{ host_media_directory  }}:/media'
    env:
      TZ: America/Eastern
      VIRTUAL_HOST: 'jellyfin.{{ hostvars[inventory_hostname].dns_name }}'
    network_mode: bridge
    networks:
      - name: docker_net