- name: Update and run docker services on sumo
  hosts: sumo
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - secrets.yml
  roles:
    - role: monitoring
    - role: unbound
    - role: jellyfin
    - role: nginx
    - role: monitored