- name: Update and run docker services on sumo
  hosts: sumo
  become: yes
  become_method: sudo
  vars_files:
    - secrets.yml
  roles:
    - role: monitoring
    - role: unbound
    - role: jellyfin
    - role: nginx
    - role: monitored
    - role: transmission