- name: Configure the wireguard server
  hosts: warden
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - secrets.yml
  tags:
    - vpn
    - warden
  roles:
    - role: dyndns
    - role: wireguard
    - role: unbound
    - role: monitored