---
- name: Update and run the mariadb container
  tags:
    - nextcloud
    - mariadb
    - database
  docker_container:
    name: mariadb
    image: mariadb:latest
    pull: yes
    recreate: yes
    restart_policy: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: "{{ mariadb_user }}"
    network_mode: bridge
    networks:
      - name: docker_net

- name: Update and run the nextcloud container
  tags:
    - nextcloud
  docker_container:
    name: nextcloud
    image: nextcloud:latest
    pull: yes
    recreate: yes
    restart_policy: always
    exposed_ports:
      - '80'
    volumes:
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - '{{ host_directory }}:/var/www/html/data'
    env:
      VIRTUAL_HOST: nextcloud.sumo.homenet
      NEXTCLOUD_TRUSTED_DOMAINS: 'nextcloud.sumo.homenet'
    network_mode: bridge
    networks:
      - name: docker_net
