---
- name: Creates unbound config directory
  tags:
    - unbound
    - dns
  file:
    path: '/var/unbound'
    state: directory

- name: Copy unbound config
  tags:
    - unbound
    - dns
  template:
    src: files/unbound.conf
    dest: /var/unbound/unbound.conf
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: Copy A record config
  tags:
    - unbound
    - dns
  template:
    src: templates/a-records.conf.j2
    dest: '/var/unbound/a-records.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: no

- name: Update and run the unbound container
  tags:
    - unbound
    - dns
  docker_container:
    name: unbound
    image: "{{ 'mvance/unbound-rpi:latest' if (is_rpi) else 'mvance/unbound:latest' }}"
    pull: yes
    recreate: yes
    restart_policy: always
    volumes:
      '/var/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf'
    ports:
      - '127.0.0.1:53:53/tcp'
      - '127.0.0.1:53:53/udp'
      - '{{ unbound_address }}:53:53/tcp'
      - '{{ unbound_address }}:53:53/udp'
    networks:
      - name: docker_net
        ipv4_address: '172.18.0.10'

- name: Wait for unbound to start
  tags:
    - unbound
    - dns
  pause:
    seconds: 30
