---
# Common settings for Fedora servers
- name: Install common utils
  dnf:
    name:
      - vim
      - jq
      - zsh
      - dnf-plugins-core
      - dnf-automatic
    state: installed

- name: Adding user jordan
  user:
    name: jordan
    group: jordan
    shell: /bin/zsh
    groups:
      - wheel
    append: yes

- name: Copy dnf-automatic config
  copy:
    src: 'files/automatic.conf'
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0600'
    backup: no

- name: Auto update
  systemd:
    name: dnf-automatic.timer
    state: started