---
- name: Create nginx config directory
  tags:
    - nginx
  file:
    path: '/var/sumo/nginx/config'
    state: directory

- name: Copy nginx config
  tags:
    - nginx
  copy:
    src: '../config/custom.conf'
    dest: '/var/sumo/nginx/config'

- name: Update and run the nginx proxy container
  tags:
    - nginx
  docker_container:
    name: nginx
    image: jwilder/nginx-proxy:latest
    pull: yes
    recreate: yes
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/sumo/nginx/config/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    ports:
      - '80:80'
    network_mode: bridge
    networks:
      - name: docker_net
