---
all:
  hosts:
  children:
    homelab:
      hosts:
        sumo:
        warden:
    dns_servers:
      hosts:
        sumo:
        warden:
#   vps:
#     hosts:
#       watchman:
#         ansible_host: jordan-hatcher.com
#         dns_name: jordan-hatcher.com