all:
  hosts:
  children:
    homelab:
      hosts:
        sumo:
          ansible_host: 192.168.0.10
          dns_name: sumo.cactusnet
        warden:
          ansible_host: 192.168.0.11
          dns_name: warden.cactusnet
          wg_pub_key: 7a/10/+U8T7XHTH5zsUUL1aZK39PZ+ujRTAE/9cTo30=
#   vps:
#     hosts:
#       watchman:
#         ansible_host: jordan-hatcher.com
#         dns_name: jordan-hatcher.com