- name: Configure the wireguard server
  hosts: warden
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - secrets.yml
    - vars.yml
  vars:
    is_server: yes
    private_ip: 10.0.0.1
    listen_port: 4997
    private_key: '{{ warden_wg_private_key }}'
    peers:
      # Phone
      - public_key: 0McW9C2yJkBbL1BMRxDHaFTejm8woSDQRnDLK/qj8kI=
        private_ip: 10.0.0.100
  tags:
    - vpn
    - warden
  roles:
    - role: dyndns
    - role: wireguard
    - role: unbound