---
- name: Update and run all docker services on sumo
  hosts: sumo
  remote_user: sumo
  vars_files:
    - secrets.yml
  tags:
    - sumo
  roles:
    - gitea
    - monitoring
    - transmission
    - role: nextcloud
      vars:
        host_directory: /var/sumo/data
    - role: jellyfin
      vars:
        host_directory: /var/sumo/data
    - role: unbound
      vars:
        is_rpi: no
        host_directory: /var/sumo/unbound
        a_records:
          - { host: sumo }
          - { subdomain: gitea, host: sumo }
          - { subdomain: monitoring, host: sumo }
          - { subdomain: transmission, host: sumo }
          - { subdomain: nextcloud, host: sumo }
          - { subdomain: jellyfin, host: sumo }
          - { host: buzzbomb }
        owner: sumo
        group: sumo
    - nginx
