---
- name: Update and run all docker services
  hosts: homeserver
  remote_user: sumo
  vars_files:
    - secrets.yml

  tasks:
    - include_role:
        name: gitea

    - include_role:
        name: nextcloud
      vars:
        host_directory: /var/sumo/data/

    - include_role:
        name: jellyfin
      vars:
        host_directory: /var/sumo/data/

    - include_role:
        name: monitoring

    - include_role:
        name: unbound
      vars:
        host_directory: /var/sumo/unbound

    - include_role:
        name: nginx