---
- name: Apply common fedora configuration to all hosts
  hosts: all
  remote_user: jordan
  vars_files:
    - secrets.yml
  roles:
    - fedora


- name: Install docker on hosts
  hosts: all
  remote_user: jordan
  vars_files:
    - secrets.yml
  tags:
    - docker
  roles:
    - docker


- name: Configure the wireguard server
  hosts: warden
  remote_user: jordan
  vars_files:
    - secrets.yml
  tags:
    - vpn
    - warden
  roles:
    - role: wireguard
      vars:
        is_server: yes
        private_ip: 10.0.0.1
        listen_port: 4997
        private_key: '{{ warden_wg_private_key }}'
        peers:
          # Phone
          - public_key: 0McW9C2yJkBbL1BMRxDHaFTejm8woSDQRnDLK/qj8kI=
            private_ip: 10.0.0.100


- name: Update and run unbound DNS server on warden
  hosts: warden
  remote_user: jordan
  vars_files:
    - secrets.yml
    - vars.yml
  tags:
    - dns
  roles:
    - role: unbound
      vars:
        is_rpi: yes


- name: Update and run docker services on sumo
  hosts: sumo
  remote_user: jordan
  vars_files:
    - secrets.yml
    - vars.yml
  roles:
    - role: unbound
      vars:
        is_rpi: no

    - role: jellyfin
      vars:
        host_media_directory: /var/media

    - role: monitoring