---
- name: Update and run all docker services on sumo
  hosts: homeserver
  remote_user: sumo
  vars_files:
    - secrets.yml
  tags:
    - sumo
  roles:
    - gitea
    - monitoring
    - transmission
    - role: nextcloud
      vars:
        host_directory: /var/sumo/data
    - role: jellyfin
      vars:
        host_directory: /var/sumo/data
    - role: unbound
      vars:
        image: mvance/unbound:latest
        host_directory: /var/sumo/unbound
        owner: sumo
        group: sumo
    - nginx
