---
- name: Update and run the influxdb container
  tags:
    - influxdb
    - database
    - monitoring
  docker_container:
    name: influxdb
    image: influxdb:latest
    pull: yes
    recreate: yes
    restart_policy: always
    volumes:
      - influxdb:/var/lib/influxdb
    exposed_ports:
      - '8086'
    env:
      VIRTUAL_HOST: 'influxdb.{{ hostvars[inventory_hostname].dns_name }}'
      INFLUXDB_ADMIN_USER: '{{ admin_user }}'
      INFLUXDB_ADMIN_PASSWORD: '{{ admin_user_password }}'
      INFLUXDB_USER: '{{ standard_user }}'
      INFLUXDB_PASSWORD: '{{ standard_user_password }}'
    networks:
      - name: docker_net

- name: Update and run the Grafana container
  tags:
    - grafana
    - monitoring
  docker_container:
    name: grafana
    image: grafana/grafana
    pull: yes
    recreate: yes
    restart_policy: always
    exposed_ports:
      - '3000'
    volumes:
      - grafana:/var/lib/grafana
    env:
      VIRTUAL_HOST: 'grafana.{{ hostvars[inventory_hostname].dns_name }}'
      #GF_SECURITY_ADMIN_USER: '{{ grafana_admin_user }}'
      #$GF_SECURITY_ADMIN_PASSWORD: '{{ grafana_admin_password }}'
    networks:
      - name: docker_net
