---
- name: Ensure the torrent download directory exists on the host
  tags:
    - transmission
    - torrent
  file:
    path: '{{ transmission_download_dir }}'
    state: directory

- name: Update and run the transmission container
  tags:
    - transmission
    - torrent
  docker_container:
    name: transmission
    image: linuxserver/transmission:latest
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - '{{ torrent_download_dir }}:/downloads'
    exposed_ports:
      - '9091'
    env:
      VIRTUAL_HOST: 'transmission.{{ hostvars[inventory_hostname].dns_name }}'
      VIRTUAL_PORT: '9091'
      USER: '{{ transmission_user }}'
      PASS: '{{ transmission_password }}'
    network_mode: bridge
    networks:
      - name: docker_net