---
# Installs docker
- name: Add docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: yes

- name: Install docker and docker python libs
  dnf:
    name:
      - docker-ce
      - python-docker-py
      - python-pip 
    state: installed
    releasever: 29 # Repo not added for Fedora 31 yet
  become: yes