---
- name: Pre-install - vscode
  become: yes
  ansible.builtin.shell: |
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install packages
  dnf:
    name:
      - vim
      - zsh
      - jq
      - keepassxc
      - code
      - gnome-tweak-tool
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    state: installed
  become: yes

- name: Change default shell to zsh
  become: yes
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh

- name: Check if oh-my-zsh is installed
  shell: '[ -d "$HOME/.oh-my-zsh" ]'
  register: cmd
  changed_when: false

- name: Install oh-my-zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: cmd.rc != 0

- name: Install custom zsh theme
  ansible.builtin.shell: |
    theme_file="$HOME/.oh-my-zsh/themes/magic-af.zsh-theme"
    if [ ! -f "$theme_file" ]
    then
      curl https://raw.githubusercontent.com/jordanhatcher/magic-af/master/magic-af.zsh-theme \
        -o "$theme_file"
    fi

- name: Ensure .gnupg directory exists
  file:
    path: /home/{{ current_user }}/.gnupg
    state: directory
- name: Copy gpg agent conf
  copy:
    dest: /home/{{ current_user }}/.gnupg/gpg-agent.conf
    src: 'files/gpg-agent.conf'
    owner: '{{ current_user }}'
    group: '{{ current_user }}'
    mode: '0644'
    backup: no

- name: Clone dotfiles repo
  git:
    repo: https://github.com/jordanhatcher/dotfiles.git
    dest: /home/{{ current_user }}/git/dotfiles

- name: Install the dotfiles
  ansible.builtin.shell: |
    cd /home/{{ current_user }}/git/dotfiles/
    ./setup.sh

- name: Install vscode extensions
  ansible.builtin.shell: |
    code --install-extension vscodevim.vim
    code --install-extension ms-python.python
    code --install-extension redhat.vscode-yaml
    code --install-extension zbr.vscode-ansible
    code --install-extension daylerees.rainglow
    code --install-extension ms-azuretools.vscode-docker
    code --install-extension shardulm94.trailing-spaces