---
- name: Ensure .gnupg directory exists
  file:
    path: /home/{{ current_user }}/.gnupg
    state: directory
- name: Copy gpg agent conf
  copy:
    dest: /home/{{ current_user }}/.gnupg/gpg-agent.conf
    content: |
      enable-ssh-support
    owner: '{{ current_user }}'
    group: '{{ current_user }}'
    mode: '0644'
    backup: no