---
- name: Pull repo for jordan-hatcher.com
  git:
    repo: https://github.com/jordanhatcher/jordan-hatcher.com.git
    dest: /var/website
    recursive: yes

- name: Run website container for jordan-hatcher.com
  tags:
    - jordan-hatcher.com
  docker_container:
    name: website
    image: klakegg/hugo:0.74.3
    restart_policy: always
    command: server
    exposed_ports:
      - '1313'
    env:
      VIRTUAL_HOST: jordan-hatcher.com,www.jordan-hatcher.com
      LETSENCRYPT_HOST: jordan-hatcher.com,www.jordan-hatcher.com
    volumes:
    - /var/website:/src
    purge_networks: yes
    networks:
      - name: docker_net