---
# Installs docker
- name: Add docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker and docker python libs
  dnf:
    name:
      - docker-ce
      - python-docker
      - python-pip
    state: installed

- name: Allow pulling from local registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": [ "sumo.cactusnet:5000" ]
      }
  register: docker_daemon_conf

- name: Start and enable docker
  systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Adding jordan to docker group
  user:
    name: jordan
    groups:
      - docker
    append: yes

- name: Create a docker network
  docker_network:
    name: docker_net
    ipam_config:
      - subnet: '172.18.0.0/16'
        gateway: '172.18.0.1'

- name: Restart docker
  service:
    name: docker.service
    state: restarted
  when: docker_daemon_conf.changed
