---
- name: Creates unbound config directory
  tags:
    - unbound
    - dns
  file:
    path: '/var/unbound'
    state: directory
  become: yes

- name: Copy unbound config
  tags:
    - unbound
    - dns
  template:
    src: templates/a-records.conf.j2
    dest: '/var/unbound/a-records.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: no
  become: yes

- name: Update and run the unbound container
  tags:
    - unbound
    - dns
  docker_container:
    name: unbound
    image: "{{ 'mvance/unbound-rpi:latest' if (is_rpi) else 'mvance/unbound:latest' }}"
    pull: yes
    recreate: yes
    restart_policy: always
    volumes:
      '/var/unbound/:/opt/unbound/etc/unbound/'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
